### ISSUE TITLE
Broken contract tests

### ISSUE THREAD

**Issue by platocrat** [ChainShot/AAVEDaiEscrow#1]
Both this project and [AAVE-Ether-Escrow](https://github.com/ChainShot/AAVE-Ether-Escrow) suffer from the same bug: an external function call error is thrown by hardhat when running the tests.

<img width="947" alt="Screen Shot 2021-01-10 at 5 09 30 PM" src="https://user-images.githubusercontent.com/37757724/104138000-9bc3c480-5366-11eb-83ed-186efae0b0b7.png">

I already confirmed this is an issue with both projects as I was following along with the examples online locally on my mac. 

**Edit:** 
Reference to the same issue in AAVE-Ether-Escrow https://github.com/ChainShot/AAVE-Ether-Escrow/issues/1#issue-782930592

**Comment by Dan-Nolan** [comment]
Hey @platocrat, thanks for bringing this up and trying out the project! 

That error message makes it seem as though it's not forking mainnet. A call to the non-contract account would be happening if it were trying to interact with the AAVE lending pool and the lending pool was not available at the address. 

I can replicate this issue if I remove the `networks` section from the `hardhat.config.js`. It should work okay out of the gate with the current configuration though. Can you tell if you're running it on a local hardhat network that is not forking mainnet?

**Comment by platocrat** [comment]
Ah, that makes sense. Yes, I was not forking mainnet (skipped that section in the README 😅).
Sorry about that!
